/**
 * Account writes and the name to id map
 *
 * Accounts are written to the PocketBase backend, and account names are
 * translated to the relation ids the server stores.
 * 
 * Accounts table:
 *    id (unique, generated by the store)
 *    user (required, relates to users table)
 *    name (required, string, unique per user)
 *    color (required, hex string)
 *    baseBalance (integer, in cents)
 *
 */

import { pb } from "./client";
import { newId } from "./ids";
import { throttledWrite } from "./throttle";
import type { AccountRecord } from "./types";

// Map of account name → id and id → name
const idByName = new Map<string, string>();
const nameById = new Map<string, string>();

const inFlight = new Map<string, Promise<string>>();

// Return the id of the currently signed in user
export function requireUserId(): string {
  const id = pb.authStore.record?.id;
  if (!id) throw new Error("Not signed in.");
  return id;
}

// Empty the maps created
export function resetAccountCache(): void {
  idByName.clear();
  nameById.clear();
  inFlight.clear();
}

// Fill the map from fetched account records
export function cacheAccounts(records: AccountRecord[]): void {
  resetAccountCache();
  for (const record of records) {
    idByName.set(record.name, record.id);
    nameById.set(record.id, record.name);
  }
}

// Look up an account id by name
export function accountIdFor(name: string): string | undefined {
  return idByName.get(name);
}

// Look up an account name by id
export function accountNameFor(id: string): string | undefined {
  return nameById.get(id);
}

// Fetch every account belonging to the signed in user
export async function fetchAccounts(): Promise<AccountRecord[]> {
  return pb.collection("accounts").getFullList<AccountRecord>({ sort: "name" });
}

// Return the id for a name
export async function ensureAccount(
  name: string,
  color: string,
  baseBalance = 0,
): Promise<string> {
  const cached = idByName.get(name);
  if (cached) return cached;

  // Two callers naming the same new account share one create,
  // the unique index on (user, name) would reject the second
  const pending = inFlight.get(name);
  if (pending) return pending;
  
  // if the account doesn't exist, create it and cache the id
  const create = throttledWrite(async () => {
    const record = await pb.collection("accounts").create<AccountRecord>({
      id: newId(),
      user: requireUserId(),
      name,
      color,
      baseBalance,
    });
    return record.id;
  })
    .then((id) => {
      idByName.set(name, id);
      nameById.set(id, name);
      return id;
    })
    .finally(() => {
      inFlight.delete(name);
    });

  inFlight.set(name, create);
  return create;
}

// Update an account's colour or base balance
export async function updateAccount(
  name: string,
  patch: { color?: string; baseBalance?: number },
): Promise<void> {
  const id = idByName.get(name);
  if (!id) throw new Error(`Unknown account "${name}".`);
  await throttledWrite(() => pb.collection("accounts").update(id, patch));
}

// Remove an account
export async function deleteAccount(name: string): Promise<void> {
  const id = idByName.get(name);
  if (!id) return;
  await throttledWrite(() => pb.collection("accounts").delete(id));
  idByName.delete(name);
  nameById.delete(id);
}
