/**
 * Description label writes
 *
 * The curated suggestion list behind the description dropdown, one per type.
 *
 * Descriptions table:
 *    id (unique, generated by the store)
 *    user (required, relates to users table)
 *    type (required, Income or Expense)
 *    label (required, string)
 *
 */

import { pb } from "./client";
import { requireUserId } from "./accounts";
import { newId } from "./ids";
import { throttledWrite } from "./throttle";
import type { TransactionType } from "../types";
import type { DescriptionRecord } from "./types";

// Add a label to the suggestion list of its type
export async function createDescription(
  type: TransactionType,
  label: string,
): Promise<void> {
  await throttledWrite(() =>
    pb.collection("descriptions").create({
      id: newId(),
      user: requireUserId(),
      type,
      label,
    }),
  );
}

// Remove a label from the suggestion list of its type
export async function deleteDescription(
  type: TransactionType,
  label: string,
): Promise<void> {
  // Find the row by type and label
  const existing = await pb
    .collection("descriptions")
    .getFullList<DescriptionRecord>({
      filter: pb.filter("type = {:type} && label = {:label}", { type, label }),
    });
  for (const record of existing) {
    await throttledWrite(() => pb.collection("descriptions").delete(record.id));
  }
}
