/**
 * Template item writes
 *
 * Recurring items the user seeds a month from, written to the PocketBase backend.
 *
 * Template_items table:
 *    id (unique, generated by the store)
 *    user (required, relates to users table)
 *    type (required, Income or Expense)
 *    amount (integer, in cents)
 *    description (required, string)
 *    account (required, references accounts table)
 *    day (optional, 1 to 31)
 *
 */

import { pb } from "./client";
import { accountIdFor, ensureAccount, requireUserId } from "./accounts";
import { throttledWrite } from "./throttle";
import type { Transaction } from "../types";

// Convert the app's date -> server day
function toDay(date: string): number | null {
  const parsed = parseInt(date, 10);
  if (Number.isNaN(parsed)) return null;
  return Math.min(Math.max(parsed, 1), 31);
}

// Convert a server day -> app's date
export function dayToDate(day: number | null | undefined): string {
  return day == null ? "" : String(day);
}

// Resolve an account by name and colour, create if it does not exist
async function resolveAccount(name: string, color: string): Promise<string> {
  return accountIdFor(name) ?? (await ensureAccount(name, color));
}

// Create a new template item in the backend
export async function createTemplateItem(
  item: Transaction,
  accountColor: string,
): Promise<void> {
  // Ensure the account exists
  const account = await resolveAccount(item.account, accountColor);
  await throttledWrite(() =>
    pb.collection("template_items").create({
      id: item.id,
      user: requireUserId(),
      type: item.type,
      amount: item.amount,
      description: item.description,
      account,
      day: toDay(item.date),
    }),
  );
}

// Update an existing template item in the backend
export async function updateTemplateItem(
  id: string,
  updates: Omit<Transaction, "id">,
  accountColor: string,
): Promise<void> {
  // Ensure the account exists
  const account = await resolveAccount(updates.account, accountColor);
  await throttledWrite(() =>
    pb.collection("template_items").update(id, {
      type: updates.type,
      amount: updates.amount,
      description: updates.description,
      account,
      day: toDay(updates.date),
    }),
  );
}

// Delete a template item from the backend
export async function deleteTemplateItem(id: string): Promise<void> {
  await throttledWrite(() => pb.collection("template_items").delete(id));
}
