/**
 * Transaction writes
 * 
 * User transactions are written to the PocketBase backend.
 * 
 * Transactions table:
 *    id (unique, generated by the store)
 *    user (required, realtes to users table)
 *    type (required, Income or Expense)
 *    amount (decimal, in cents)
 *    description (required, string)
 *    account (required, references accounts table)
 *    date (required, date string)
 * 
 */

import { pb } from "./client";
import { accountIdFor, ensureAccount, requireUserId } from "./accounts";
import { newId } from "./ids";
import { throttledWrite } from "./throttle";
import type { Transaction } from "../types";

// Resolve an account by name and color, creating it if it doesn't exist
async function resolveAccount(name: string, color: string): Promise<string> {
  return accountIdFor(name) ?? (await ensureAccount(name, color));
}

// Create a new transaction in the backend
export async function createTransaction(
  tx: Transaction,
  accountColor: string,
): Promise<void> {
  // Ensure the account exists
  const account = await resolveAccount(tx.account, accountColor);
  await throttledWrite(() =>
    pb.collection("transactions").create({
      id: tx.id,
      user: requireUserId(),
      type: tx.type,
      amount: tx.amount,
      description: tx.description,
      account,
      date: tx.date,
    }),
  );
}

// Update an existing transaction in the backend
export async function updateTransaction(
  id: string,
  updates: Omit<Transaction, "id">,
  accountColor: string,
): Promise<void> {
  // Ensure the account exists
  const account = await resolveAccount(updates.account, accountColor);
  await throttledWrite(() =>
    pb.collection("transactions").update(id, {
      type: updates.type,
      amount: updates.amount,
      description: updates.description,
      account,
      date: updates.date,
    }),
  );
}

// Delete a transaction from the backend
export async function deleteTransaction(id: string): Promise<void> {
  await throttledWrite(() => pb.collection("transactions").delete(id));
}

// Generate a new unique transaction ID
export function newTransactionId(): string {
  return newId();
}
